### PR TITLE
Create 'Work with Us' page with frontend developer offer

### PR DESCRIPTION
**Pull request by oriolbcn**
Hi guys!

I created a page to show the new front-end developer offer :) better than going around with a PDF.

In the "Work with Us" intro I mention Basecamp to reference our company culture. I wanted to link it to a blog post or page or something where Basecamp explains their company culture, but have not managed to find any.

## Other things

* I added the ability to define custom body classes for a page, a part from a class generated from the URL. This way, we can change the URL without affecting the body class.
* I changed the link of the "Join the Martians!" button in the Team page to point to this new Work with Us page. Not really sure if it's a good idea.
* Added a new element to the navigation bar to point to the new page. We could also remove it and just have the page floating around with no direct link, but I think it's beneficial to link it explicitly.

### "Join the Martians!" link on the Team page

 I changed the link of the "Join the Martians!" button in the Team page to point to this new Work with Us page. Not really sure if it's a good idea. Opinions are welcome.

### Salary

Personally, when I look at a job offer I value A LOT that there are specific numbers for the salary, so I added the specific salary range to the job description. 

**This is for you to remove if you don't want to show it, or change with the appropriate numbers** (or tell me the numbers and I'll change it) cc/ @jvendrell 

### Styles

I added a new Stylesheet to be able to style the page easily, maybe @javierartero can take a look and spend no more than 30 minutes to style a little bit more, I just added some basic styling.

### CODE REVIEW

**Comment by javierartero** [comment]
Looks good !!

@oriolbcn i have applied small changes:
- Set the maximum width to 800 px in the content.
- hr tag after each block
- Removed the red color in the titles
- Modified main title, it is not a good idea to create a small tag with a display block:inside a h1, for this is used the hgroup tag is more semantic.
- Added general hgroup styles

**Comment by oriolbcn** [comment]
Great!! Looking much better now, thanks! 😄

**Comment by xredo** [comment]
Hey, I think that this is a very good idea. And opening a PR to be able to discuss it's even better 👍  

Here are my thoughts.

### Section title

I believe that _Work with us_ could be ambiguous. It could refer to both clients and future employees. I'm more fond of using _Jobs_ as the section title. I think it's a pretty standard practice:

https://basecamp.com/about/jobs
https://www.shopify.com/jobs
https://redbooth.com/jobs
http://jobs.wuaki.tv

Regarding SEO, the url name is: we-are-hiring-frontend-developer, which is going to be cool for now but I don't know future implications. Maybe @alexrodba can throw some light here.

### Menu priority

I prefer adding this new section after the Blog one. @alexrodba If we have this section here while the offer is active and then we remove it, It will impact SEO somehow? I'm not very fond of having a Jobs section in the menu stating that we don't have current job opportunities.

### H1

Maybe we can use a friendlier title like: _Become a Martian_. WDYT?

**Comment by alexrodba** [comment]
This is fantastic, Oriol. Thanks.

As for SEO, it's ok. I'd also link it directly, but maybe not in the top navbar. Maybe a link in the footer? We don't hire very often (or at least, we don't plan to) and the section isn't a big deal in our website for now.

I like "Become a Martian" for the H1. Go for it. I'd also add the salary range.

**Comment by oriolbcn** [comment]
Thanks for the feedback!!

Changes applied:
* Changed section title to Jobs.
* Removed from main navbar.
* Changed H1 ( @xredo the H1 I changed was the one you refered to, right?)

TODO:

* Add link in the footer. @javierartero can to take care of it please? no hurry
* If everyone agrees with salary range, add correct salary range. Responisble @jvendrell or @xredo

**Comment by jvendrell** [comment]
I've made some fixes:

- The header now takes the full width like it happens in other pages.
- I've fixed the salary range.
- Added a subtitle Open positions
- Added the Jobs link to the footer.
- Replaced the URL slug for jobs.

I'm merging this to master.

**Comment by oriolbcn** [comment]
AWESOME 😍  good job team!!

**Pull request merged**
